### ISSUE TITLE
(1.7.5.4) Does not show data for pitch timing and dynamics

### ISSUE THREAD

**Issue by ILuvGemz** [sigprogramming/tyouseisientool#18]
Version 1.7.5.4

I had added in the timing pitch and dynamics, but they never get shown in here. What did I do wrong?

<img width="1166" alt="image" src="https://github.com/sigprogramming/tyouseisientool/assets/76889022/44a7944b-5104-4087-9fe9-36062e1ff986">

**Comment by sigprogramming** [comment]
Thank you for your question!

Timing, pitch, and dynamics are not displayed in score edit mode.
It would be possible to implement the ability to display these, but since the code is becoming more complex, i am planning to implement this in the new editor that i am currently working on.

Also, v1.7.x is not currently maintained.
I am releasing [v1.8.x and v1.9.x](https://github.com/sigprogramming/tyouseisientool/releases), which allow for automatic rendering and are compatible with v1.2.x and later NEUTRINO, so I recommend using the v1.8.x or v1.9.x tools unless you intend to use earlier NEUTRINO versions.
Please note that v1.8.x is compatible with NEUTRINO v1 and v1.9.x with NEUTRINO v2.
